# Generated by Django 3.1.7 on 2021-03-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parcial', '0002_auto_20210314_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre_categoria',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_categoria',
            new_name='nombre',
        ),
    ]
